
language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - vendor

before_script:
  - phpenv config-rm xdebug.ini
  - composer install --prefer-source

script:
  - ./vendor/bin/phpunit