version: '2'
networks:
  default:
    external:
      name: docker-compose
services:
  app:
    image: eu.gcr.io/g4m-docker-images/cloud-sdk-docker
    volumes:
    - .:/app
    environment:
    - APP_MODE=DEV
    restart: always
    ports:
    - "8001:8000"
    - "8081:8080"
    links:
      - elasticsearch
    command:
      ["dev_appserver.py", "/app/app.local.yaml", "--php_executable_path", "/usr/bin/php5-cgi", "--host", "0.0.0.0", "--admin_host", "0.0.0.0"]
    networks:
      default:
        aliases:
        - g4m-elastic-proxy.local.dev.g4m.co.uk
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ports:
    - "9200:9200"

